---
title: "Personality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(data.table))
```

```{r Read_data}
raw_data <- read_csv("../data/Relationship between blood group and personality.csv")
head(raw_data)
```

```{r CLean_up}
# Missing data count for each column
na_count <-sapply(raw_data, function(y) sum(length(which(is.na(y)))))
(na_count <- data.frame(na_count))

#Converting all factor columns to class character
raw_data <- raw_data %>% group_by_if(is.factor, as.character)

# We do not need the Timestamp for analysis, we can drop the column as it is the timestamp of when the individual has taken the survey. Dropping it .
raw_data<- subset(raw_data, select = - c(Timestamp)) 

#Sane column names
new_names <- c("Origin","Reside","Age","Gender","BldGrp","InRel","BldGrp_Prtnr",
               "help_Ppl","Enyj_Grp","Chs_Wrds_Care", "Take_Chrg","Get_Nervs_Talkng","Like_Ordr",
               "Get_Upset","Modest_Achieve","Adventure","Enjy_attentn","Variety_Routine",
               "Feel_Emo","Hard_Trust_Ppl","Avoid_Arguing","Avoid_alone","Detail_Orntd",
               "Focus_on_present","Go_With_Flow","Talk_abt_Own_Feelngs","Fun_Party_Aftr_Wrk",
               "Rarely_Insecure")

### Reference table of column names ###
(Col_names<-data.frame(stringsAsFactors=FALSE,old_names = c(colnames(raw_data)),new_names))
#Col_names <- Col_names %>% group_by_if(is.factor, as.character)

### Updating col. names ###
setnames(raw_data, Col_names$old_names, Col_names$new_names)
colnames(raw_data)

#Formatting strings
raw_data$Origin<-str_to_title(raw_data$Origin)   # Example : INDIA to become India
raw_data$Origin<-trimws(raw_data$Origin)         # Trimming leading/trailing spaces

raw_data$Reside<-str_to_title(raw_data$Reside)   # Example : INDIA to become India
raw_data$Reside<-trimws(raw_data$Reside)         # Trimming leading/trailing spaces

# Filter out "A+" as Origin
raw_data<- raw_data%>% filter(raw_data$Origin != "A+" & raw_data$Origin !="Côte D'ivoire \U0001f1e8\U0001f1ee")
raw_data<- raw_data%>% filter(raw_data$Reside != "\U0001f1fa\U0001f1f8" & raw_data$Reside !="United State Usa \U0001f1fa\U0001f1f8")


#Getting the unique values from columns 
(unique(raw_data$Origin))  
(unique(raw_data$Reside))
(unique(raw_data$Age))

```

```{r}
#Spell check
(corrected <- data.frame(stringsAsFactors=FALSE,
     Wrong_spell = c("Ivory Coast", 
                     "Côte D'ivoire", 
                     "Ivoiry Coast", 
                     "Côte D' Ivoire",    
                     "Côté D'ivoire",
                     "Cote D'ivoire", 
                     "Cote D Ivoire", 
                     "Côté D'ivoire",
                     "Niger",
                     "Usa",
                     "Côte D'ivoire \U0001f1e8\U0001f1ee",
                     "Drc",
                     "Cote D'ivoire",
                     "Côte D Ivoire",
                     "Côte D'ivoire",
                     "Côté D Ivoire",
                     "Côte Divoire",
                     "Dr Congo",
                     "United States",
                     "Sénégal",
                     "Côte D'ivoire",
                     "Côte D'ivoire",
                     "Nigeri",
                     "Nigerian",
                     "The Democratic Republic Of Congo",
                     "United States Of America",
                     "Cote D'ivoire",
                     "Afrique",
                     "Us",
                     "United State",
                     "U.s",
                     "Uae",
                     "Cite D D'ivoire",
                     "United State Usa \U0001f1fa\U0001f1f8",
                     "African",
                     "United Kingdom",
                     "Uk",
                     "\U0001f1fa\U0001f1f8",
                     "Unites States",
                     "USA Of America",
                     "USA USA \U0001f1fa\U0001f1f8",
                     "Hong Kong Sar",
                     "America",
                     "Cameroun",
                     "Dallas",
                     "England",
                     "Lagos",
                     "Yes"
                    ),
     Correct_spell = c("Ivory Coast", 
                       "Ivory Coast", 
                       "Ivory Coast", 
                       "Ivory Coast", 
                       "Ivory Coast",
                       "Ivory Coast", 
                       "Ivory Coast",
                       "Ivory Coast",
                       "Nigeria",
                       "USA",
                       "Ivory Coast",
                       "Congo",
                       "Ivory Coast",
                       "Ivory Coast",
                       "Ivory Coast",
                       "Ivory Coast",
                       "Ivory Coast",
                       "Congo",
                       "USA",
                       "Senegal",
                       "Ivory Coast",
                       "Ivory Coast",
                       "Nigeria",
                       "Nigeria",
                       "Congo",
                       "USA",
                       "Ivory Coast",
                       "Africa",
                       "USA",
                       "USA",
                       "UAE",
                       "Ivory Coast",
                       "USA",
                       "Africa",
                       "USA",
                       "UK",
                       "UK",
                       "Unknown",
                       "USA",
                       "USA",
                       "USA",
                       "Hong Kong",
                       "USA",
                       "Cameroon",
                       "USA",
                       "UK",
                       "Nigeria",
                       "Ivory Coast"
                       )
))


(regex_pattern <- setNames(corrected$Correct_spell, paste0("\\b",corrected$Wrong_spell,"\\b")))
raw_data$Origin<-str_replace_all((raw_data$Origin), regex_pattern)
raw_data$Reside<-str_replace_all((raw_data$Reside), regex_pattern)



# Age handling
raw_data$Age<- ifelse(raw_data$Age %in% c("31 years old",
                                           "26 ans",
                                           "29 ans",
                                           "Almost 22",
                                           "18-45",
                                           "23 years old",
                                           "34+",
                                           "27 years old",
                                           "30 Years"
                                          ),
                                         c("31","26","29","22","20","23","34","27","30"),
                                          raw_data$Age)
#raw_data$Age<-str_replace_all((raw_data$Age), regex_pattern)

#Checking the unique values from columns 
(unique(raw_data$Origin))
(unique(raw_data$Reside))
(unique(raw_data$Age))

#Age column to numeric
raw_data$Age <- as.numeric(raw_data$Age)
head(raw_data)

#Chechking if any column has any NAs after update
na_count <-sapply(raw_data, function(y) sum(length(which(is.na(y)))))
(na_count <- data.frame(na_count))
```

```{r}
#Age group creation
AgeGroup <- cut(raw_data$Age, 
                right=FALSE, 
                breaks = c(0,1,(1:5)*10,1000),
                labels = c("0","1-5",
                           paste((1:4)*10,"-",(1:4 + 1)*10 -1),"50+"))


raw_data<-mutate(raw_data,AgeGroup=AgeGroup)

head(raw_data)
```



```{r write file}
#View(raw_data)
#Write file
write.csv(raw_data,"../data/Relationship_bloodGrp_cleaned.csv", row.names = FALSE)

```




